server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
foo: foo version 7002 change
spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 106.12.197.38
    port: 5672
    virtual-host: my_vhost
    username: zhou
    password: 644721
  sleuth:
    sampler:
      #设置Sleuth的抽样收集概率，1.0为百分之100%上传
      probability: 1
    web:
      enabled: true
  zipkin:
    sender:
      type: rabbit
# Admin 管理配置
management:
  endpoints:
    web:
      exposure:
        # 开启了 'refresh' 端点
        include: '*'
  endpoint:
    health:
      show-details: always
management:
  security:
    enabled: false
logging:
  file:
    name: "logs/boot-admin-sample.log"
  
