server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
foo: foo version 7002
spring:
  rabbitmq:
    host: 106.12.197.38
    port: 5672
    username: zhou
    password: 644721
management:
  security:
    enabled: false
