server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
foo: foo version 7002 change
spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 106.12.197.38
    port: 5672
    virtual-host: my_vhost
    username: zhou
    password: 644721
# Admin 管理配置
management:
  endpoints:
    web:
      exposure:
        # 开启了 'refresh' 端点
        include: '*'
  endpoint:
    health:
      show-details: always
  
