server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
foo: foo version 7002 change
spring:
  rabbitmq:
    host: 106.12.197.38
    port: 5672
    virtual-host: my_vhost
    username: zhou
    password: 644721
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
